def Agent_snapshot(String name) {
    withCredentials([usernamePassword(credentialsId: 'scribe-backend-auth0-id', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD'),
                     usernamePassword(credentialsId: 'scribe-aws-cred-id', usernameVariable: 'AWS_AKID', passwordVariable: 'AWS_SECRET')]) {
      def out_data = sh(script: """agent snapshot -r=true --failonerror -vv -u ${params.SCRIBE_URL} -n ${name} -U ${USERNAME} -P ${PASSWORD} \
      --log.cloudwatch.enable=true \
      --log.cloudwatch.AKID=${AWS_AKID} \
      --log.cloudwatch.secret=${AWS_SECRET}
      """,returnStdout: true)
      println out_data
    }
}


pipeline {
  agent {
    kubernetes {
      yamlFile 'jenkins_k8s/agenttest_scribe_simple/KubernetesPod.yaml'
    }
  }
  
  parameters {
      gitParameter(name: 'BRANCH_NAME',
          branchFilter: 'origin/(.*)',
          selectedValue: 'NONE',
          defaultValue: 'master',
          type: 'PT_BRANCH')

      string(defaultValue: 'https://api.dev.scribesecurity.com', 
        name: 'SCRIBE_URL', 
        trim: true)
  }

    environment {
        GIT_AUTHOR_NAME = 'jenkins_git_user'
        GIT_AUTHOR_EMAIL = 'jenkins_git_user@mail.com'
    }

  stages {
    stage('Busybox') {
       steps {
        container('busybox') {
            sh 'echo test > some_stage_create_file.txt'
          }
        container('agent') {
          Agent_snapshot("Post-Busybox")
        }        
      }
    }
    stage('Git') {
      steps {
        container('git') {
            sh 'git version'
            sh '''echo test2 > some_stage_create_file.txt'''
        }
        container('agent') {
          Agent_snapshot("Post-git")
        }
      }
    }
  }
}
