configs:
  - name: bomber
    signer:
        fulcio:
            enable: true
            url: https://fulcio.sigstore.dev
            oidc:
                auth: provider
	        			issuer: https://token.actions.githubusercontent.com
                clientid: sigstore
    storer:
      rekor:
          enable: true
          url: https://rekor.sigstore.dev
          disablebundle: false
  - name: pre-commit-slsa-verify
    verifier:
        fulcio:
            enable: true
        certemails:
            - nogoodmail2.com
            - my-sigstore-service@android-distancing.iam.gserviceaccount.com
    storer:
      rekor:
          enable: true
          url: https://rekor.sigstore.dev
          disablebundle: false
