def Agent_snapshot(String name) {
    withCredentials([usernamePassword(credentialsId: 'scribe-backend-auth0-id', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD'),
                     usernamePassword(credentialsId: 'scribe-aws-cred-id', usernameVariable: 'AWS_AKID', passwordVariable: 'AWS_SECRET')]) {
      def out_data = sh(script: """agent snapshot -r=true  -vv -u ${params.SCRIBE_URL} -n ${name} -U ${USERNAME} -P ${PASSWORD} \
      --log.cloudwatch.enable=true \
      --log.cloudwatch.AKID=${AWS_AKID} \
      --log.cloudwatch.secret=${AWS_SECRET} \
       --snapshot.file.enable=true \
       --snapshot.bomber.enable=true \
       --snapshot.bomber.hookfile=^.*.tar\$ 
      """,returnStdout: true)
      println out_data
      PublishSnapshots(env.STAGE_NAME)
    }
}

def ListJson(String snapshot_directory) {
    def json_files
    dir (snapshot_directory) {
      json_files = findFiles(glob: """*.json""")
    }
    return json_files
}

def PublishSnapshots(String name, String directory="scribe/agent/output") {
    def file_list = []
    try {    
      def timestamp = readFile directory + '/DIR_TIMESTAMP'
      def snapshot_directory = directory + '/events/' + name + '/' + timestamp
      sh 'echo dir: $snapshot_directory'
      sh 'ls -lhR scribe'
      for (f in  ListJson(snapshot_directory)) {
        if (! f.directory) {
          echo """Publishing ${f.name} ${f.path} ${f.directory} ${f.length} ${f.lastModified}"""
          file_list.add(f.path)
        }
      }
      def obj_list_files
      obj_list_files = ListJson(snapshot_directory)
      echo 'Snapshot files: ' + snapshot_directory + "," + file_list + "," +  obj_list_files

      publishHTML (target : [allowMissing: false,
          alwaysLinkToLastBuild: true,
          keepAll: true,
          reportDir: snapshot_directory,
          reportFiles: obj_list_files.join(','),
          reportName: name])
    }
    catch (Exception e) {
      echo 'Exception occurred: ' + e.toString()
    }
}


pipeline {
  agent {
    kubernetes {
      yamlFile 'jenkins_k8s/agenttest_scribe_demo_p1_2/KubernetesPod.yaml'
    }
  }

  parameters {
      gitParameter(name: 'BRANCH_NAME',
          branchFilter: 'origin/(.*)',
          selectedValue: 'NONE',
          defaultValue: 'master',
          type: 'PT_BRANCH')

      string(defaultValue: 'https://api.dev.scribesecurity.com',
        name: 'SCRIBE_URL',
        trim: true)
  }

    environment {
        GIT_AUTHOR_NAME = 'jenkins_git_user'
        GIT_AUTHOR_EMAIL = 'jenkins_git_user@mail.com'
    }

  stages {
    stage('XBusybox') {
       steps {
        container('busybox') {
            sh 'echo test > some_stage_create_file.txt'
            sh 'echo Danny has three apples > fruit.txt'
            sh 'echo Sunday > days.txt'
          }
        container('agent') {
          Agent_snapshot("sample-test1")
          
            
        }
      }
    }
    stage('XGit') {
      steps {
        container('git') {
            sh 'git version'
            sh '''echo test2 > some_stage_create_file.txt'''
            sh 'echo and two oranges >> fruit.txt'
            sh 'echo Tuesday > days.txt'
        }
        container('agent') {
          Agent_snapshot("sample-test2")
        }
      }
    }
      stage('Python') {
      steps {
        container('python') {
            sh '''#!/bin/bash
            set -x
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install argparse==1.3.0
            pip install pillow==8.3.1
            pip install pyopenssl==17.0.1
            pip install pycurl'''
        }
        container('agent') {
            Agent_snapshot("sample")
            sh 'rm -rf venv'
       }
      }
    }
  }
}
