name: scribe agent

env:
  SCRIBE_DEFAULT_URL: https://api.dev.scribesecurity.com

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      url:
        description: 'Scribe url'
        required: false
        default: 'https://api.dev.scribesecurity.com'

jobs:
  scribe-agent:
    runs-on: ubuntu-latest
    container:
      image: scribesecuriy.jfrog.io/scribe-docker-local/agent:0.0.18
      credentials:
        username: github
        password: ${{ secrets.scribe_artifactory_cred_id }}
    steps:
    - run: echo "Hello ${{ github.event.inputs.url }}!"
    - name: Checkout source
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - run: agent --version
    - run: printenv
    - run: agent snapshot -vv -n github-push -u ${{ github.event.inputs.url || env.SCRIBE_DEFAULT_URL }} -U scribe -P ${{ secrets.scribe_backend_basic_id }} -H github