name: scribe agent

env:
  SCRIBE_DEFAULT_URL: https://api.dev.scribesecurity.com

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      url:
        description: 'Scribe url'
        required: false
        default: 'https://api.dev.scribesecurity.com'

jobs:
  scribe-agent:
    runs-on: ubuntu-latest
    container:
      image: scribesecuriy.jfrog.io/scribe-docker-local/agent:latest
      credentials:
        username: github
        password: ${{ secrets.scribe_artifactory_cred_id }}
    steps:
    - run: echo "Hello ${{ github.event.inputs.url }}!"
    - name: Checkout source
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - run: agent --version
    - run: printenv
    - name: Agent sample files metadata
        if: env.TYPE == file
        run: |
          run: agent snapshot -vv -n github-push -u ${{ github.event.inputs.scribe_url || env.SCRIBE_DEFAULT_URL }} -t ${{ secrets.scribe_backend_token_id }} -H github

    - name: Run snapshot files and artifactory
        if: env.SNAPSHOT_TYPE == file_artifactory
        run: |
          run: agent snapshot -vv -n github-push -u ${{ github.event.inputs.scribe_url || env.SCRIBE_DEFAULT_URL }} -t ${{ secrets.scribe_backend_token_id }} -H github

    # - run: agent snapshot -vv -n github-push -u ${{ github.event.inputs.url || env.SCRIBE_DEFAULT_URL }} -U scribe -P ${{ secrets.scribe_backend_basic_id }} -H github
    #- run: agent snapshot -vv -n github-push -u ${{ github.event.inputs.url || env.SCRIBE_DEFAULT_URL }} -T ${{ secrets.scribe_backend_token_id }} -H github
