name: scribe agent

on:
  push:
  pull_request:
  workflow_dispatch:
  inputs:
    name:
      description: 'Person to greet'
      required: true
      default: 'Mona the Octocat'
    home:
      description: 'location'
      required: false
      default: 'The Octoverse'

jobs:
  scribe-agent:
    runs-on: ubuntu-latest
    container:
      image: scribesecuriy.jfrog.io/scribe-docker-local/agent:latest
      credentials:
        username: github
        password: ${{ secrets.scribe_artifactory_cred_id }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - run: agent --version
    - run: printenv
    - run: agent snapshot -vv -n github-push -t ${{ secrets.scribe_backend_token_id }} -H github
